
spring:
  profiles:
    active: dev
    
    
    
    
# 声名式客户端配置
forest:
  # 连接池最大连接数
  max-connections: 1000
  # 连接超时时间，单位为毫秒
  connect-timeout: 10000
  # 数据读取超时时间，单位为毫秒
  read-timeout: 3000
  log-enabled: true            # 打开或关闭日志（默认为 true）
  log-request: true            # 打开/关闭Forest请求日志（默认为 true）
  log-response-status: true    # 打开/关闭Forest响应状态日志（默认为 true）
  log-response-content: true   # 打开/关闭Forest响应内容日志（默认为 false）
